name: Code Coverage

on:
  push:
    branches: [ '**' ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/.gitignore'
      - '**/README*'
      - '.github/**'
      - '**/src/test/**'

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and check coverage
      run: |
        mvn clean verify \
          -Dmaven.javadoc.skip=true \
          -Dmaven.source.skip=true \
          -Djacoco.haltOnFailure=true

    - name: Upload JaCoCo report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/
        retention-days: 7
