name: Manual release build and push to GPR

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Build with Maven
        run: |
          mvn -B clean verify
          mvn -B spotless:check
        
      - name: Publish to GitHub Packages
        run: |
          mvn -B deploy -DskipTests \
            -Dmaven.javadoc.skip=true \
            -Dmaven.source.skip=true \
            -Dmaven.test.skip=true \
            -Dmaven.install.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: insurance-api
          path: target/*.jar
          retention-days: 30
